sudo: required
language: r
cran: https://cran.rstudio.com/
matrix:
  include:
  - os: linux
    dist: trusty
    r: oldrel
    addons:
      apt:
        packages:
          - libgdal1-dev
          - libproj-dev
  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        packages:
          - libgdal1-dev
          - libproj-dev
    r_binary_packages:
      - covr
    r_github_packages:
      - jimhester/lintr
    after_success:
    - Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
    - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: trusty
    r: devel
    addons:
      apt:
        packages:
          - libgdal1-dev
          - libproj-dev
  - os: osx
    osx_image: xcode8.2
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
    before_script:
    - Rscript -e "install.packages('rgdal', type = 'source')"
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
branches:
  only:
    - master
    - development
    - testing
